### ISSUE TITLE
testui darkmode bug

### ISSUE THREAD

**Issue by Myeser** [razerragin21/Just-Get-Started#37]
**Describe the bug**
testui automatically says light mode wehn opened but starts in dark mode

**To Reproduce**
open testui

**Expected behavior**
testui opens in light mode or it says dark mode when opened

**Screenshots**
![image](https://user-images.githubusercontent.com/93088450/207936518-e7a2394a-782b-4707-816b-f73ed982f95f.png)

**Desktop (please complete the following information):**
 - OS: win10

**Comment by razerragin21** [comment]
Fixed in latest push
